### ISSUE TITLE
Outdated readme

### ISSUE THREAD

**Issue by PaulRill00** [lukeheath/nestjs-shopify#1]
Hey, I found this Github Repo. But after following your readme, I found out I installed the wrong npm package.
After doing some research I found your package here: https://www.npmjs.com/package/nestjs-shopify-wrapper.

Turns out, your npm package is named differently then what is stated on your readme on GitHub. I would suggest you update it, as this is working wonders!

**Comment by lukeheath** [comment]
Hey, sorry I missed your issue. I didn't realize anyone was using this! Thanks for calling this out. I've updated the readme. Strangely enough, someone else published the npm `nestjs-shopify` package between the time I created this repo and published the package, so I had to go with `nestjs-shopify-wrapper`.
